[[DebianGlibc]]
arch = "aarch64"
git-tree-sha1 = "f36c7e93d4fd3dde69759aad9004f9b9e83d3e36"
libc = "glibc"
os = "linux"

    [[DebianGlibc.download]]
    sha256 = "cc97eeee3bba259a3fbb66a64bdf299f0f3d0fb3d3aa83d2372f9246ed3f5f50"
    url = "https://github.com/JuliaBinaryWrappers/DebianGlibc_jll.jl/releases/download/DebianGlibc-v2.33.0+1/DebianGlibc.v2.33.0.aarch64-linux-gnu.tar.gz"
