# Autogenerated wrapper script for DebianGlibc_jll for aarch64-linux-gnu
JLLWrappers.@generate_wrapper_header("DebianGlibc")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@generate_init_footer()
end  # __init__()
